### Importing the Packages

In [1]:
import pandas as pd
import numpy as np

### Importing the data

In [2]:
raw_csv_data = pd.read_csv("Index2018.csv") 
df_comp=raw_csv_data.copy()

### Lenght of the Time Period

In [3]:
df_comp.describe()

               spx           dax         ftse        nikkei
count  6269.000000   6269.000000  6269.000000   6269.000000
mean   1288.127542   6080.063363  5422.713545  14597.055700
std     487.586473   2754.361032  1145.572428   4043.122953
min     438.920000   1911.700000  2876.600000   7054.980000
25%     990.671905   4069.350000  4486.100000  10709.290000
50%    1233.420000   5773.340000  5662.430000  15028.170000
75%    1459.987747   7443.070000  6304.250000  17860.470000
max    2872.867839  13559.600000  7778.637689  24124.150000

In [4]:
df_comp.head()

         date     spx      dax     ftse    nikkei
0  07/01/1994  469.90  2224.95  3445.98  18124.01
1  10/01/1994  475.27  2225.00  3440.58  18443.44
2  11/01/1994  474.13  2228.10  3413.77  18485.25
3  12/01/1994  474.17  2182.06  3372.02  18793.88
4  13/01/1994  472.47  2142.37  3360.01  18577.26

In [5]:
df_comp.date.describe()

count           6269
unique          6269
top       07/01/1994
freq               1
Name: date, dtype: object

### From Text to Date

In [6]:
df_comp.date = pd.to_datetime(df_comp.date, dayfirst = True)

In [7]:
df_comp.head()

        date     spx      dax     ftse    nikkei
0 1994-01-07  469.90  2224.95  3445.98  18124.01
1 1994-01-10  475.27  2225.00  3440.58  18443.44
2 1994-01-11  474.13  2228.10  3413.77  18485.25
3 1994-01-12  474.17  2182.06  3372.02  18793.88
4 1994-01-13  472.47  2142.37  3360.01  18577.26

In [8]:
df_comp.date.describe()

count                          6269
mean     2006-01-14 19:36:59.492742
min             1994-01-07 00:00:00
25%             2000-01-11 00:00:00
50%             2006-01-12 00:00:00
75%             2012-01-19 00:00:00
max             2018-01-29 00:00:00
Name: date, dtype: object

### Setting the Index

In [10]:
df_comp.set_index("date", inplace = True)

In [11]:
df_comp.head()

               spx      dax     ftse    nikkei
date
1994-01-07  469.90  2224.95  3445.98  18124.01
1994-01-10  475.27  2225.00  3440.58  18443.44
1994-01-11  474.13  2228.10  3413.77  18485.25
1994-01-12  474.17  2182.06  3372.02  18793.88
1994-01-13  472.47  2142.37  3360.01  18577.26

In [ ]:
#df_comp.date.describe() #Expect to get an error message because we no longer have a "date" column since it is the index

### Setting the Desired Frequency

In [13]:
df_comp=df_comp.asfreq('D')

In [14]:
df_comp.head()

               spx      dax     ftse    nikkei
date
1994-01-07  469.90  2224.95  3445.98  18124.01
1994-01-08     NaN      NaN      NaN       NaN
1994-01-09     NaN      NaN      NaN       NaN
1994-01-10  475.27  2225.00  3440.58  18443.44
1994-01-11  474.13  2228.10  3413.77  18485.25

In [ ]:
df_comp=df_comp.asfreq('b')

In [ ]:
df_comp.head()

               spx      dax     ftse    nikkei
date
1994-01-07  469.90  2224.95  3445.98  18124.01
1994-01-10  475.27  2225.00  3440.58  18443.44
1994-01-11  474.13  2228.10  3413.77  18485.25
1994-01-12  474.17  2182.06  3372.02  18793.88
1994-01-13  472.47  2142.37  3360.01  18577.26

### Handling Missing Values

In [15]:
df_comp.isna().sum()

spx       2520
dax       2520
ftse      2520
nikkei    2520
dtype: int64

In [17]:
df_comp.spx=df_comp.spx.ffill()

In [18]:
df_comp.isna().sum()

spx          0
dax       2520
ftse      2520
nikkei    2520
dtype: int64

In [19]:
df_comp.ftse=df_comp.ftse.bfill()

In [20]:
df_comp.dax=df_comp.dax.fillna(value = df_comp.dax.mean())

In [21]:
df_comp.isna().sum()

spx          0
dax          0
ftse         0
nikkei    2520
dtype: int64

### Simplifying the Dataset

In [22]:
df_comp['market_value']=df_comp.spx

In [23]:
df_comp.describe()

               spx           dax         ftse        nikkei  market_value
count  8789.000000   8789.000000  8789.000000   6269.000000   8789.000000
mean   1288.624342   6080.063363  5423.766500  14597.055700   1288.624342
std     488.039397   2326.164026  1145.822421   4043.122953    488.039397
min     438.920000   1911.700000  2876.600000   7054.980000    438.920000
25%     990.637242   4839.460000  4489.670000  10709.290000    990.637242
50%    1234.180000   6080.063363  5662.430000  15028.170000   1234.180000
75%    1460.250000   6739.300000  6302.300000  17860.470000   1460.250000
max    2872.867839  13559.600000  7778.637689  24124.150000   2872.867839

In [24]:
del df_comp['spx']

In [25]:
df_comp.describe()

                dax         ftse        nikkei  market_value
count   8789.000000  8789.000000   6269.000000   8789.000000
mean    6080.063363  5423.766500  14597.055700   1288.624342
std     2326.164026  1145.822421   4043.122953    488.039397
min     1911.700000  2876.600000   7054.980000    438.920000
25%     4839.460000  4489.670000  10709.290000    990.637242
50%     6080.063363  5662.430000  15028.170000   1234.180000
75%     6739.300000  6302.300000  17860.470000   1460.250000
max    13559.600000  7778.637689  24124.150000   2872.867839

In [26]:
del df_comp['dax']
del df_comp['ftse']
del df_comp['nikkei']

In [27]:
df_comp.describe()

       market_value
count   8789.000000
mean    1288.624342
std      488.039397
min      438.920000
25%      990.637242
50%     1234.180000
75%     1460.250000
max     2872.867839

### Splitting the Data

In [28]:
size = int(len(df_comp)*0.8)

In [29]:
df = df_comp.iloc[:size]

In [30]:
df_test = df_comp.iloc[size:]

In [31]:
df.tail()

            market_value
date
2013-04-03   1553.686978
2013-04-04   1559.979316
2013-04-05   1553.278930
2013-04-06   1553.278930
2013-04-07   1553.278930

In [32]:
df_test.head()

            market_value
date
2013-04-08   1563.071269
2013-04-09   1568.607909
2013-04-10   1587.731827
2013-04-11   1593.369863
2013-04-12   1588.854623